fix(changelog): vendor clog and allow setting a tag date
plouc/nivo pull request #1278
Opened 2020-11-13 21:48 UTC by wyze

Close #1277 

-----

If you check the referenced ticket, I point to the code where the date is always set to the current date. I pulled down the code and made the changes needed to support the date.

Looks like this also changed the order of Features/Bug Fixes sections and added colons to the component names.

Alternatively, we could look at something else to generate these like https://github.com/conventional-changelog/conventional-changelog, but the output might not be exactly the same. Seems clog hasn't received updates in some time.

2020-11-16 13:24 UTC, plouc commented
Yes, this issue is annoying, I don't think we should include the tool directly into the repo though, I'd prefer to find another tool, even if the output is slightly different.

2020-11-16 14:30 UTC, wyze commented
Okay, that works for me. I will evaluate a few and see which ones work best and update the PR, maybe with a few samples.

2020-11-17 00:38 UTC, wyze commented
@plouc Should be good to go now. I'd like to squash this into a single commit on merge.

2020-11-17 13:19 UTC, plouc requested changes

2020-11-17 13:19 UTC, plouc commented on scripts/generate-changelog.js
>  const fetchTags = () =>
I think we could add some comments about how it works/what's happening here, it's a bit difficult to understand, for example explaining the format used for git log and how it's used in the regexp.

2020-11-17 13:19 UTC, plouc commented on scripts/generate-changelog.js
>  const run = async () => {
Same here, I know it was already undocumented, but it's not straightforward, for example by defining the structure of `tags`, what do you think?

2020-11-17 14:09 UTC, plouc approved these changes
LGTM

2020-11-17 14:10 UTC, merged