Add nice prop to bar
plouc/nivo pull request #1282
Opened 2020-11-16 05:21 UTC by ericsoco

I noticed that `ResponsiveBar` charts with many, narrow bars were varying in width. The `svg` container was the correct width, but the bars within it were offset from the left/right edges.

Screencap:
![nivo-bar-nicing](https://user-images.githubusercontent.com/1127259/99215624-5f218580-2788-11eb-80fb-9ac23ea4f703.gif)

After some digging, I narrowed it down to the use of `d3-scale.scaleBand.rangeRound()` within `Bar`'s `common.js::getIndexedScale()`. This diff puts this nicing behavior behind a `nice` prop, which defaults to `true` to maintain current functionality unless a developer opts out with `nice=false`.

The above test with `nice=false`:
![nivo-bar-nicing-off](https://user-images.githubusercontent.com/1127259/99215646-6d6fa180-2788-11eb-8348-febca38234e5.gif)

I didn't add anything to the Bar demo site; I can if you like, but this prop feels niche / edge-case enough that it may not need to be surfaced in the demo site.

2020-11-16 06:29 UTC, plouc commented
@ericsoco seems interesting to have the option, however I'm not sure about the naming, having `nice` as a prop on the top level component is hard to figure out I think, maybe something like `roundIndexScale`? This should also be added to the TypeScript definitions, ideally I'd like to have everything documented, but the way the website works is not documented, so I can definitely understand if you don't want to :) It would also be nice to add a unit test for it.

2020-11-16 12:58 UTC, wyze commented
I agree about the prop name. Something like `indexScale={{ nice?: boolean, round?: boolean }}` to be more flexible to accept future options if needed.

2020-11-17 22:45 UTC, ericsoco commented
@plouc -- I can look into added to TS defs and a unit test; can also take a look at adding to the website if it's not too complex!

Also, I realize now that `nice` is slightly different semantically than `rangeRound` ([docs](https://github.com/d3/d3-scale)), so agreed on naming; can take @wyze's approach and refactor to `indexScale={round}`. I'll leave out "nice" for now, can add in the future if useful.

2020-11-17 22:48 UTC, plouc commented
Thank you @ericsoco! Yes @wyze approach is more flexible and align with the `valueScale` we already have.

2020-11-18 05:29 UTC, plouc requested changes

2020-11-18 05:29 UTC, plouc commented on packages/scales/index.d.ts
> +    export interface IndexedScale {
This should be a `BandScale` to match d3 types.

2020-11-18 05:29 UTC, plouc commented on packages/scales/src/index.js
> +    PropTypes.shape(indexedScalePropTypes),
Would have to be renamed to `bandScalePropTypes`.

2020-11-18 05:29 UTC, plouc commented on packages/scales/src/indexedScale.js
> +export const indexedScalePropTypes = {
This should be `bandScalePropTypes`.

2020-11-18 05:29 UTC, plouc commented on packages/bar/index.d.ts
> +        indexedScale: Scale
I think it would be better to call it `indexScale`, the scale type is a bandScale, and is used for indexes.

2020-11-18 05:31 UTC, plouc commented
@ericsoco Thank you for the adjustments, maybe what we suggested was confusing, the property should be `indexScale`, to be consistent with `valueScale` (we cannot really use x/y scale for names as the chart supports different layouts), but the scale type is a band scale.

2020-11-18 05:31 UTC, ericsoco commented
No worries, I can make these changes now (and fix the failing lint).

2020-11-18 07:43 UTC, plouc requested changes

2020-11-18 07:43 UTC, plouc commented on packages/bar/src/compute/common.js
> +export const getIndexedScale = (data, getIndex, range, padding, indexScale) => {
nit: I think we could also rename this to `getIndexScale()`.

2020-11-18 07:43 UTC, plouc commented on packages/bar/src/compute/stacked.js
> +    const indexedScale = getIndexedScale(data, props.getIndex, range, padding, indexScale)
Maybe `indexScale` and `indexScaleConfig`, as you did before?

2020-11-18 07:43 UTC, plouc commented on packages/bar/src/props.js
> +    indexScale: scalePropType.isRequired,
Actually, we should use `bandScalePropTypes` as other scale types aren't supported.

2020-11-18 07:43 UTC, plouc commented on packages/bar/index.d.ts
> +        indexScale: Scale
We should restrict to BandScale here, otherwise it might give the impression that other types are supported too.

2020-11-18 13:03 UTC, wyze requested changes
Also need to update the canvas implementation to pass the value through to the generate bars methods or it will crash. I made the mistake with valueScale :O.

https://github.com/plouc/nivo/blob/484235ff44bf3cb516e906f8c2b101669b17fc8a/packages/bar/src/BarCanvas.js#L58

2020-11-18 16:53 UTC, ericsoco commented
![Uploading nivo-bar-indexScale.gif…]()

2020-11-18 17:21 UTC, wyze requested changes
Code looks really good! https://dlqum.sse.codesandbox.io/bar/

Only minor change is I think we should change the website values to default to the default values of the component.

2020-11-18 17:21 UTC, wyze commented on website/src/pages/bar/api.js
> +                    indexScale: { type: 'band', round: false },
```suggestion
                    indexScale: { type: 'band', round: true },
```

2020-11-18 17:21 UTC, wyze commented on website/src/pages/bar/canvas.js
> +    indexScale: { type: 'band', round: false },
```suggestion
    indexScale: { type: 'band', round: true },
```

2020-11-18 17:21 UTC, wyze commented on website/src/pages/bar/index.js
> +    indexScale: { type: 'band', round: false },
```suggestion
    indexScale: { type: 'band', round: true },
```

2020-11-18 17:36 UTC, ericsoco commented
@wyze oof good catch! Fixed.

2020-11-18 18:07 UTC, wyze approved these changes
Looks great! Thanks. https://z5c1z.sse.codesandbox.io/bar/

2020-11-18 22:47 UTC, plouc approved these changes
LGTM

2020-11-18 22:49 UTC, merged

2020-11-18 22:50 UTC, plouc commented
Thank you @ericsoco!

2020-11-19 03:50 UTC, ericsoco commented
Thank _you_ @plouc for the lovely library, and @wyze as well 😄

2021-01-17 20:09 UTC, jamesdh commented
@ericsoco I'm looking back at this issue and I see your bar chart uses time series data for its X-axis but I don't see any way to do so without converting their value to a string (which causes every bar to have a tick). Can any one of you guys clarify how that was done?

2021-01-17 23:37 UTC, ericsoco commented
I have string values for x-axis formatted as `YYYY-MM`, and I'm passing `xFormat: 'time:%Y-%m'` to `ResponsiveBar`.

I don't have a tick on every bar because I'm not using Nivo to render the x-axis labels / ticks, this is a hybrid component that functions as a slider (using Material-UI) with a bar chart overlaid.

I think what I just told you is probably not helpful for your use case...sorry!