feat(sunburst): use arcs package
plouc/nivo pull request #1350
Opened 2020-12-16 11:53 UTC by plouc

:warning: Depends on the arcs package PR

2020-12-18 18:03 UTC, wyze requested changes

2020-12-18 18:09 UTC, wyze commented on packages/sunburst/tests/Sunburst.test.tsx
> +        xit('should support patterns', () => {
It seems like the changes to `bindDefs` cause this to fail. What is the reason behind those changes?

2020-12-28 00:13 UTC, plouc commented on packages/sunburst/src/types.ts
>  export type SunburstArcProps<RawDatum> = Pick<
Good catch! Removed.

2020-12-28 00:13 UTC, plouc commented on packages/sunburst/src/types.ts
>  export type SunburstLabelProps<RawDatum> = {
Good catch! Removed.

2021-01-07 15:45 UTC, wyze approved these changes

2021-02-20 20:35 UTC, TheMatrixMaster commented
When will this PR be merged?

2021-03-02 15:53 UTC, TheMatrixMaster approved these changes

2021-04-23 19:39 UTC, merged