Upgrade react-spring, fix for #1290
plouc/nivo pull request #1480
Opened 2021-04-14 16:43 UTC by jamesdh

Upgrades from react-spring @ 9.0.0-rc3 to 9.0.1 Fixes #1290, or at least appears to do so when running in storybook. 

I have to imagine a lot of people stumbled upon this bug and rather than looking or a solution as described in #1290, they simply downgraded. After accidentally running into it again today I decided it's time to see if a fix is available, so here you go!

2021-04-15 09:00 UTC, rap2hpoutre commented
Thank you so much @jamesdh! Hopefully, it will be merged soon (not sure the project is still actively maintained though).

2021-04-20 11:54 UTC, rogemus commented
@plouc Any chance for you to take a quick look?

2021-04-21 12:54 UTC, wyze requested changes
Hi @jamesdh, would you mind upgrading to the latest version of the package? Looks like it is now `9.1.1`. Thanks!

2021-04-21 13:26 UTC, rogemus commented on packages/annotations/package.json
> +    "react-spring": "9.0.1"
Can we use `^9.1.0` version here and in all other packages as well?

2021-04-23 15:16 UTC, wyze commented
@jamesdh I saw you upgraded to the latest and that broke the build. I was working on fixing the errors and didn't know if you were as well. I'll continue working on it and push my changes here.

2021-04-23 15:24 UTC, jamesdh commented
@wyze @plouc @rogemus I originally used 9.0.1 because I knew it should just be a drop-in replacement that works for now. 9.1.x was out when I first submitted this PR, but I saw in its release notes that it contained breaking changes and I didn't want to bother with them for the time being. 

I just tried upgrading to 9.1.2 and sure enough, it causes numerous breakages during the build. I say we just merge this for now since [using 9.0.0.rc3 is problematic beyond just this script issue](https://github.com/plouc/nivo/issues/1472#issuecomment-816909820):

> My company has a proxy around NPM that only releases stable packages. They won't release react-spring 9.0.0-rc.3. So I haven't been able to work with the latest versions of Nivo

Then we can then do another PR that contains the extra work to get 9.1.x working.

2021-04-23 15:25 UTC, jamesdh commented
> @jamesdh I saw you upgraded to the latest and that broke the build. I was working on fixing the errors and didn't know if you were as well. I'll continue working on it and push my changes here.

@wyze I just force-pushed a revert back to 9.0.1. See my comment above.

2021-04-23 15:47 UTC, wyze commented
Thats fine. I reapplied your patch of the upgrade and then did another commit that fixes the type errors. This allowed the build to pass locally, so we will see what CI says.

2021-04-23 17:07 UTC, wyze approved these changes
Looks good! Thanks.

2021-04-23 17:08 UTC, merged