feat(stream): add ability to customize legend label
plouc/nivo pull request #1562
Opened 2021-06-02 00:37 UTC by wyze

Close #323

2021-06-02 00:53 UTC, wyze commented
Here is an example of intended functionality: https://codesandbox.io/s/nivo-forked-ove5e?file=/src/charts/Stream.tsx

2021-06-02 21:49 UTC, plouc requested changes

2021-06-02 21:49 UTC, plouc commented on website/src/data/components/stream/props.js
> +        type: 'string | (datum: RawDatum): string',
I don't think the type of `datum` is correct as [we just pass the `id`](https://github.com/plouc/nivo/pull/1562/files#diff-44b3698944ddca2af8ad0c22a159233c92c88739e99d018b7a9b9f09f345dfb6R107) if I understand correctly, maybe we could use an inlined type such as `(datum: { id: string }): string`?

2021-06-02 21:49 UTC, plouc commented on packages/stream/index.d.ts
> +        legendLabel: PropertyAccessor<T, string>
I don't think we can use `T` here.

2021-06-02 21:49 UTC, plouc commented on packages/stream/index.d.ts
> +        borderColor: InheritedColorConfig<T>
The structure you'll get when defining `borderColor` is:
```ts
interface ComputedDatum {
    id: number
    layer: {
        index: number
        x: number
        value: number
        y1: number
        y2: number
    }[] 
    path: string
    color: string
}
```

2021-06-02 21:49 UTC, plouc commented on packages/stream/index.d.ts
> +        dotColor: InheritedColorConfig<T>
I think custom accessors for the dots will receive the following structure:

```ts
interface DotDatum {
    key: string
    id: number
    color: string
    index: number
    x: number
    value: number
    y1: number
    y2: number
}
```

Apparently `Datum`, in the definitions file.

It's a combination of [what's computed for the layer points](https://github.com/plouc/nivo/blob/master/packages/stream/src/hooks.js#L91), and some extra properties passed in https://github.com/plouc/nivo/blob/master/packages/stream/src/StreamDots.js#L35.

2021-06-03 12:25 UTC, plouc approved these changes
LGTM

2021-06-03 12:26 UTC, merged