feat(sunburst): add `innerRadius` and `renderRootNode` props
plouc/nivo pull request #2219
Opened 2023-01-13 18:38 UTC by 0x706b

Updated PR based on #1794

- Adds a prop similar to the pie chart's `innerRadius` prop to change the size of the sunburst chart's inner circle.
- Adds a prop to render the root node in the center of the chart.

Fixes #1649

2023-07-24 18:50 UTC, BEEFF commented
Please merge

2023-08-23 19:02 UTC, sohamsshah commented
@0x706b Seems this branch has conflicts for merging. Can you please resolve them?

@plouc Thanks for this amazing library. This feature is something I am actively looking forward to be added. If this code looks good, can we please add this to sunburst chart? (Pardon for tagging) Please let me know if I can do anything from my end for this PR.

2024-01-15 11:37 UTC, petrvecera commented
I was just looking for this feature 👍

2024-01-17 07:19 UTC, uson1x commented
Looking forward for this PR 🙌  or the other rebased one

2024-11-24 20:09 UTC, nass600 commented
@plouc Any news about this PR?

2024-12-30 09:47 UTC, uson1x commented
My new years wish is for this PR to be merged 🤞

2025-03-16 05:55 UTC, plouc requested changes

2025-03-16 05:55 UTC, plouc commented on pnpm-lock.yaml
I don't think the lock file should contain that many changes.

2025-04-14 14:01 UTC, closed without merging