feat(radar): add onClick handler
plouc/nivo pull request #2601
Opened 2024-05-31 15:19 UTC by Nino3103

## Radar Chart : add onClick handler

- added onClick props in Radar props
- adjusted the types to accept onClick in Radar props
- added a story in Radar storybook with onClick

## Issue : https://github.com/plouc/nivo/issues/1003

## Video
https://github.com/plouc/nivo/assets/48714971/edc20b8a-df04-4cdb-85d2-49efb8b8ce90

2024-06-20 12:41 UTC, charles-glanceable commented
We are really looking forward to this new feature! Thank you 👍

2024-07-03 01:03 UTC, plouc requested changes
Overall, LGTM, thank you.

However the property should be added to the website (I'm not sure we need a story), also it would be good to add some tests for this new feature.

2024-07-04 09:49 UTC, Nino3103 commented
Thank you for your answer, I will add it to the website and add some tests 👍 Should I remove the story ?

2024-07-04 17:07 UTC, Nino3103 commented
Hello @plouc , I added a radar test and updated the website


https://github.com/plouc/nivo/assets/48714971/d5653a24-3606-4681-9707-d077aa178fa1

2024-07-04 23:49 UTC, plouc requested changes

2024-07-04 23:49 UTC, plouc commented on packages/radar/tests/Radar.test.tsx
> +        // const wrapper = mount(<Radar<TestDatum> {...baseProps} />)
Should be removed :)

2024-07-04 23:49 UTC, plouc commented on storybook/stories/radar/Radar.stories.tsx
> +
I think it can be removed as it's now included to the website, less to maintain :)

2024-07-05 04:54 UTC, Nino3103 commented on packages/radar/tests/Radar.test.tsx
> +        // const wrapper = mount(<Radar<TestDatum> {...baseProps} />)
I removed the commented line (231) :)

2024-07-05 07:51 UTC, Nino3103 commented
@plouc I've resync with master, tests are passing now 👍

2024-07-05 07:56 UTC, merged

2024-07-05 07:57 UTC, plouc commented
@Nino3103, thank you for your contribution!