Add colors and colorBy to common props
plouc/nivo pull request #2651
Opened 2024-09-24 07:43 UTC by lemps

I was creating a custom layer for my bar chart and didn't find a way to access the colours passed to the chart.

Figured that the most correct approach is to actually pass `colors` and `colorBy` props to the layer so I could use `const getColor = useOrdinalColorScale(colors, colorBy)` in my custom layer.

2024-09-24 08:07 UTC, plouc commented
`getColor` is already returned by the `useBar` hook, so I'd suggest to pass this instead of recomputing the same color scale inside the custom layer.

2024-09-24 08:29 UTC, lemps commented
Thanks for the feedback. Updated the PR to pass getColor along instead

2024-09-26 09:43 UTC, plouc requested changes

2024-09-26 09:43 UTC, plouc commented on packages/bar/src/types.ts
> +    getColor: OrdinalColorScaleConfig<ComputedDatum<RawDatum>>
The type is `OrdinalColorScale<ComputedDatum<RawDatum>>` at this point it's not the config anymore.

2024-10-24 08:30 UTC, tombennet commented
@plouc This would be useful for us too - can we get this one merged? Thanks!

2024-10-24 11:50 UTC, plouc approved these changes
LGTM

2024-10-24 11:58 UTC, merged